version: "3"

services:
  client:
    build:
      context: ./client
    ports:
      - "5173:5173" # Expose the client app port
    depends_on:
      - backend # Wait for the backend service to be ready before starting the client
    networks:
      - backend_network

  backend:
    build:
      context: ./backend
    ports:
      - "3001:3001"
    depends_on:
      - mysql # Wait for the MySQL database service to be ready before starting the backend
    networks:
      - backend_network
    restart: always
    environment:
      MYSQL_USER: root
      MYSQL_HOST: mysql
      MYSQL_DATABASE: video_app
      MYSQL_PASSWORD: azad4582
      MYSQL_PORT: 3306
      PORT: 3001

  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: azad4582
      MYSQL_DATABASE: video_app
      MYSQL_PASSWORD: azad4582
    ports:
      - "3306:3306"
    restart: always

networks:
  backend_network:
    driver: bridge
