version: "3"
services:
  mysql:
    image: mysql:latest
    container_name: mysql-1
    ports:
      - "3306:3306"
    networks:
      - backend_default
    environment:
      MYSQL_ROOT_PASSWORD: azad4582
      MYSQL_DATABASE: video_app

  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nodejs-1
    ports:
      - "3001:3001"
    networks:
      - backend_default
    depends_on:
      - mysql

networks:
  backend_default:
