name: Node.js CI/CD

on:
  push:
    branches: ["test"]

jobs:
  build:
    runs-on: self-hosted
    strategy:
      matrix:
        node-version: [20.x]

    steps:
      - uses: actions/checkout@v3
      - name: Retry Checkout
        run: git checkout -f ${{ github.sha }}
      - name: Full Git Fetch
        run: git fetch --prune --unshallow
      - name: Clean and Reset
        run: |
          git clean -ffdx
          git reset --hard ${{ github.sha }}
      - name: Retry Checkout Again
        run: git checkout -f ${{ github.sha }}
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm ci
      - run: |
          touch .env
          echo "${{ secrets.PROD_ENV_FILE }}" > .env
      - name: Create private key file
        run: echo "${{ secrets.SSH_PRIVATE_KEY }}" > cyf.pem
      - name: Set correct permissions for the private key file
        run: chmod 600 cyf.pem
      - name: SSH into EC2 and restart server
        run: |
          ssh -o StrictHostKeyChecking=no -i "cyf.pem" ubuntu@ec2-13-41-69-27.eu-west-2.compute.amazonaws.com "cd ~/actions-runner-backend/_work/cyf-cloud-video-saver/cyf-cloud-video-saver && npm install && pm2 restart cyf"
